BALLBERRY_GS = 2
LEUNING_GS = 3

BADGERCOLLATZ = 1
BERNACCI = 0

SOILDATA_POTENTIAL = 1     # SOIL MOISTURE DATA IS POTENTIAL (MPa)
SOILDATA_DEFICIT   = 2     # SOIL MOISTURE DATA IS DEFICIT (DIMNLESS)
SOILDATA_CONTENT   = 3     # SOIL MOISTURE IS CONTENT (m3 m-3), as when simulated.
SOILDATA_SIMULATED = 4     # 
SOILDATA_NONE      = 0     # NO SOIL MOISTURE DATA

photosynlib = dlopen(joinpath(ENV["MAESPA"], "physiol"))
